/*
    Copyright 2022 Jeffrey Sharp

    Permission to use, copy, modify, and distribute this software for any
    purpose with or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

using System.Diagnostics;

namespace Subatomix.Diagnostics;

using static ActivityIdFormat;

internal static class ActivityExtensions
{
    internal static void SetStatusIfUnset(this Activity activity, Exception? exception)
    {
        if (activity is null)
            throw new ArgumentNullException(nameof(activity));

        if (activity.Status != ActivityStatusCode.Unset)
            return;

        var (code, description) = exception is not null
            ? (ActivityStatusCode.Error, exception.Message)
            : (ActivityStatusCode.Ok,    null);

        activity.SetStatus(code, description);
    }

    internal static void GetRootOperationId(this Activity activity, Span<char> chars)
    {
        activity
            .GetRootOperationId()
            .FillLettersAndDigits(chars);
    }

    internal static string GetRootOperationId(this Activity activity)
    {
        if (activity is null)
            throw new ArgumentNullException(nameof(activity));

        return activity.IdFormat == W3C
            ? activity.GetRootOperationIdW3C()
            : activity.GetRootOperationIdFallback();
    }

    internal static Guid GetRootOperationGuid(this Activity activity)
    {
        if (activity is null)
            throw new ArgumentNullException(nameof(activity));

        return activity.IdFormat == W3C
            ? ParseHexAsGuid(activity.GetRootOperationIdW3C())
            : SynthesizeGuid(activity.GetRootOperationIdFallback());
    }

    private static string GetRootOperationIdW3C(this Activity activity)
    {
        var id = activity.TraceId;
        if (id == default)
            throw MakeNotStartedException();

        return id.ToHexString();
    }

    private static string GetRootOperationIdFallback(this Activity activity)
    {
        var id = activity.RootId;
        if (id is null)
            throw MakeNotStartedException();

        return id;
    }

    private static Guid ParseHexAsGuid(string s)
    {
        const string HexDigitsFormat = "N";

        return Guid.ParseExact(s, HexDigitsFormat);
    }

    internal static Guid SynthesizeGuid(string s)
    {
        // NOTE: The GUIDs generated by this method are not even remotely
        // cryptographically secure.  Do NOT use this for cryptography.

        // 'reg' is a linear feedback shift register.
        // Info: https://en.wikipedia.org/wiki/Linear-feedback_shift_register
        ulong reg = 0xD91E_8A62_B35A_7D6E; // meaningless nonzero seed

        // 'bit' has the XOR of register bits 0, 2, 5, and 7 in its bit 0.
        // On each iteration, this bit shifts into the high bit of 'reg'.
        ulong bit;

        // Consume the input, injecting its entropy into the LFSR
        foreach (var character in s.AsSpan())
        {
            bit  = (reg >> 0) ^ (reg >> 2) ^ (reg >> 5) ^ (reg >> 7);
            reg  = (reg >> 1) | (bit << 63);
            reg += character;
        }

        // Begin assembling the GUID
        Span<byte> bytes = stackalloc byte[16];

        // Run the LFSR to generate a GUID's worth of pseudo-random bytes
        for (var index = 0; index < bytes.Length; index++)
        {
            // 8 rounds of LFSR generates 8 random bits
            for (var round = 0; round < 8; round++)
            {
                bit = (reg >> 0) ^ (reg >> 2) ^ (reg >> 5) ^ (reg >> 7);
                reg = (reg >> 1) | (bit << 63);
            }

            bytes[index] = (byte) reg;
        }

        // Microsoft GUIDs actually are 'version 4, variant 1' UUIDs as
        // described by RFC4122 and other standards.  Compliant GUIDs have
        // the following format:
        // 
        // xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx
        //
        // where
        //   M is 4
        //   N is 8, 9, A, or B

        // Fixup to become RFC4122-compliant
        bytes[7] &= 0b_00001111;
        bytes[7] |= 0b_01000000;
        bytes[8] &= 0b_00111111;
        bytes[8] |= 0b_10000000;

        // Assemble the GUID
#if NET6_0_OR_GREATER
        return new Guid(bytes);
#else
        return new Guid(bytes.ToArray());
#endif
    }

    private static Exception MakeNotStartedException()
    {
        return new InvalidOperationException(
            "Cannot get root operation id for an unstarted Action."
        );
    }
}
